// This file is auto-generated by dfx generate
// Stub file for development - will be replaced when running: dfx generate backend

export const idlFactory = ({ IDL }) => {
  const TimeZone = IDL.Record({
    'id': IDL.Text,
    'name': IDL.Text,
    'utcOffset': IDL.Int,
  });
  const UserProfile = IDL.Record({
    'principal': IDL.Principal,
    'name': IDL.Text,
    'homeTimeZone': TimeZone,
  });
  const Recurrence = IDL.Variant({
    'weekly': IDL.Null,
    'biweekly': IDL.Null,
    'monthly': IDL.Null,
  });
  const Shift = IDL.Record({
    'id': IDL.Nat,
    'startTime': IDL.Int,
    'endTime': IDL.Int,
    'recurrence': IDL.Opt(Recurrence),
    'notes': IDL.Text,
    'meetingLink': IDL.Text,
    'hostName': IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin': IDL.Null,
    'user': IDL.Null,
    'guest': IDL.Null,
  });
  const ShiftStats = IDL.Record({
    'totalShifts': IDL.Nat,
    'claimedShifts': IDL.Nat,
    'unclaimedShifts': IDL.Nat,
  });
  const AssociateSummary = IDL.Record({
    'name': IDL.Text,
    'claimedShifts': IDL.Nat,
  });
  const AdminSummary = IDL.Record({
    'shiftStats': ShiftStats,
    'associateSummaries': IDL.Vec(AssociateSummary),
  });
  return IDL.Service({
    '_initializeAccessControlWithSecret': IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole': IDL.Func([IDL.Principal, UserRole], [], []),
    'claimShift': IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createShift': IDL.Func([IDL.Int, IDL.Int, IDL.Opt(Recurrence), IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteShift': IDL.Func([IDL.Nat], [], []),
    'editIndividualInstance': IDL.Func([IDL.Nat, IDL.Int, IDL.Int, IDL.Text, IDL.Text], [], []),
    'editShift': IDL.Func([IDL.Nat, IDL.Int, IDL.Int, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAdminSummary': IDL.Func([], [AdminSummary], ['query']),
    'getCallerUserProfile': IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole': IDL.Func([], [UserRole], ['query']),
    'getClaimQueue': IDL.Func([], [IDL.Vec(Shift)], ['query']),
    'getPublicShifts': IDL.Func([], [IDL.Vec(Shift)], ['query']),
    'getShifts': IDL.Func([], [IDL.Vec(Shift)], ['query']),
    'getUserProfile': IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin': IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile': IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
