import { useState, useEffect } from 'react';
import { Actor, HttpAgent } from '@dfinity/agent';
import { useInternetIdentity } from './useInternetIdentity';
// @ts-ignore - generated by dfx
import { idlFactory } from 'declarations/backend/backend.did.js';
import type { _SERVICE } from 'declarations/backend/backend.did';

const BACKEND_CANISTER_ID = process.env.CANISTER_ID_BACKEND || 
  import.meta.env.CANISTER_ID_BACKEND || '';

const HOST = process.env.DFX_NETWORK === 'ic' 
  ? 'https://icp-api.io' 
  : 'http://127.0.0.1:4943';

export function useActor() {
  const { identity } = useInternetIdentity();
  const [actor, setActor] = useState<_SERVICE | null>(null);
  const [isFetching, setIsFetching] = useState(true);

  useEffect(() => {
    async function createActor() {
      setIsFetching(true);
      try {
        const agent = await HttpAgent.create({
          identity: identity || undefined,
          host: HOST,
        });

        // Fetch root key for local development
        if (process.env.DFX_NETWORK !== 'ic') {
          await agent.fetchRootKey().catch(console.error);
        }

        const newActor = Actor.createActor<_SERVICE>(idlFactory, {
          agent,
          canisterId: BACKEND_CANISTER_ID,
        });
        
        setActor(newActor);
      } catch (error) {
        console.error('Failed to create actor:', error);
      } finally {
        setIsFetching(false);
      }
    }

    createActor();
  }, [identity]);

  return { actor, isFetching };
}
